left_link1:
  limit:
    lower: -1.396263
    upper: 3.490659
    velocity: 16.754666
    effort: 40

left_link2:
  limit:
    lower: -1.745329
    upper: 1.745329
    velocity: 16.754666
    effort: 40

left_link3:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 5.445426
    effort: 27

left_link4:
  limit:
    lower: 0.0
    upper: 2.443461
    velocity: 5.445426
    effort: 27

left_link5:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 20.943946
    effort: 7

left_link6:
  limit:
    lower: -0.785398
    upper: 0.785398
    velocity: 20.943946
    effort: 7

left_link7:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 20.943946
    effort: 7


right_link1:
  limit:
    lower: -1.396263
    upper: 3.490659
    velocity: 16.754666
    effort: 40

right_link2:
  limit:
    lower: -1.745329
    upper: 1.745329
    velocity: 16.754666
    effort: 40

right_link3:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 5.445426
    effort: 27

right_link4:
  limit:
    lower: 0.0
    upper: 2.443461
    velocity: 5.445426
    effort: 27

right_link5:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 20.943946
    effort: 7

right_link6:
  limit:
    lower: -0.785398
    upper: 0.785398
    velocity: 20.943946
    effort: 7

right_link7:
  limit:
    lower: -1.570796
    upper: 1.570796
    velocity: 20.943946
    effort: 7