base_link:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

left_wheel_link:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

right_wheel_link:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

link1:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

link2:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

link3:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0