left_wheel_link:
  limit:
    lower: 0
    upper: 0
    velocity: 0
    effort: 0

right_wheel_link:
  limit:
    lower: 0
    upper: 0
    velocity: 0
    effort: 0

link1:
  limit:
    lower: 0
    upper: 0.2
    velocity: 100
    effort: 100

link2:
  limit:
    lower: 0
    upper: 0.2
    velocity: 100
    effort: 100

link3:
  limit:
    lower: 0
    upper: 0.2
    velocity: 100
    effort: 100