left_hand:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

right_hand:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

left_left_finger:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

left_right_finger:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

right_left_finger:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0

right_right_finger:
  kinematic:
    xyz: 0.0 0.0 0.0
    rpy: 0.0 0.0 0.0